// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/src/misc.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa2cce8ec02104d8, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Once struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Once) Reset()         { *m = Once{} }
func (m *Once) String() string { return proto.CompactTextString(m) }
func (*Once) ProtoMessage()    {}
func (*Once) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa2cce8ec02104d8, []int{1}
}

func (m *Once) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Once.Unmarshal(m, b)
}
func (m *Once) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Once.Marshal(b, m, deterministic)
}
func (m *Once) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Once.Merge(m, src)
}
func (m *Once) XXX_Size() int {
	return xxx_messageInfo_Once.Size(m)
}
func (m *Once) XXX_DiscardUnknown() {
	xxx_messageInfo_Once.DiscardUnknown(m)
}

var xxx_messageInfo_Once proto.InternalMessageInfo

func (m *Once) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Many struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Many) Reset()         { *m = Many{} }
func (m *Many) String() string { return proto.CompactTextString(m) }
func (*Many) ProtoMessage()    {}
func (*Many) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa2cce8ec02104d8, []int{2}
}

func (m *Many) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Many.Unmarshal(m, b)
}
func (m *Many) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Many.Marshal(b, m, deterministic)
}
func (m *Many) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Many.Merge(m, src)
}
func (m *Many) XXX_Size() int {
	return xxx_messageInfo_Many.Size(m)
}
func (m *Many) XXX_DiscardUnknown() {
	xxx_messageInfo_Many.DiscardUnknown(m)
}

var xxx_messageInfo_Many proto.InternalMessageInfo

func (m *Many) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "api.Void")
	proto.RegisterType((*Once)(nil), "api.Once")
	proto.RegisterType((*Many)(nil), "api.Many")
}

func init() {
	proto.RegisterFile("api/src/misc.proto", fileDescriptor_fa2cce8ec02104d8)
}

var fileDescriptor_fa2cce8ec02104d8 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2c, 0xc8, 0xd4,
	0x2f, 0x2e, 0x4a, 0xd6, 0xcf, 0xcd, 0x2c, 0x4e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4e, 0x2c, 0xc8, 0x54, 0x62, 0xe3, 0x62, 0x09, 0xcb, 0xcf, 0x4c, 0x51, 0x92, 0xe0, 0x62, 0xf1,
	0xcf, 0x4b, 0x4e, 0x15, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0x31, 0x95, 0x64, 0xb8, 0x58, 0x7c, 0x13, 0xf3, 0x2a, 0x85, 0x44, 0xb8, 0x58, 0x0b,
	0x4b, 0x53, 0x8b, 0x60, 0x72, 0x10, 0x8e, 0x93, 0x52, 0x94, 0x42, 0x7a, 0x66, 0x49, 0x4e, 0x62,
	0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x7a, 0x7e, 0x62, 0x4e, 0x62, 0x7a, 0xaa, 0x7e, 0x69, 0x49,
	0x66, 0x4e, 0x66, 0x49, 0x66, 0x6a, 0xb1, 0x7e, 0x62, 0x41, 0x66, 0x12, 0x1b, 0xd8, 0x3e, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x27, 0x8c, 0x22, 0x85, 0x00, 0x00, 0x00,
}
